#!/usr/bin/env bash
# Shared defaults for Skill-3D scripts. Scripts may override any value through
# environment variables before sourcing or before invocation.

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
  echo "common_env.sh must be sourced, not executed." >&2
  exit 2
fi

SKILL3D_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="${PROJECT_ROOT:-$(cd "${SKILL3D_SCRIPT_DIR}/.." && pwd)}"
MODEL_ROOT="${MODEL_ROOT:-${PROJECT_ROOT}/model_links}"
DATA_ROOT="${DATA_ROOT:-${PROJECT_ROOT}/dataset}"
OUTPUT_ROOT_BASE="${OUTPUT_ROOT_BASE:-${PROJECT_ROOT}/results}"
LOG_ROOT="${LOG_ROOT:-${PROJECT_ROOT}/logs}"
MEMORY_ROOT="${MEMORY_ROOT:-${PROJECT_ROOT}/statics/skill3d_shared}"

export PROJECT_ROOT MODEL_ROOT DATA_ROOT OUTPUT_ROOT_BASE LOG_ROOT MEMORY_ROOT

export XDG_CACHE_HOME="${XDG_CACHE_HOME:-${PROJECT_ROOT}/.cache}"
export HF_HOME="${HF_HOME:-${XDG_CACHE_HOME}/huggingface}"
export TRITON_CACHE_DIR="${TRITON_CACHE_DIR:-${XDG_CACHE_HOME}/triton}"

export SKILL3D_RETRIEVAL_MODEL="${SKILL3D_RETRIEVAL_MODEL:-${SPAGENT_RETRIEVAL_MODEL:-${MODEL_ROOT}/Qwen3-Embedding-0.6B}}"
export SPAGENT_RETRIEVAL_MODEL="${SPAGENT_RETRIEVAL_MODEL:-${SKILL3D_RETRIEVAL_MODEL}}"
export SPAGENT_RL_RETRIEVAL_TOP_K="${SPAGENT_RL_RETRIEVAL_TOP_K:-6}"
export SPAGENT_STOP_ON_ANSWER="${SPAGENT_STOP_ON_ANSWER:-1}"
export SPAGENT_ENFORCE_MUST_TRY_TOOLS="${SPAGENT_ENFORCE_MUST_TRY_TOOLS:-0}"

export OPENAI_RECOVERY_MAX_ATTEMPTS="${OPENAI_RECOVERY_MAX_ATTEMPTS:-0}"
export OPENAI_RECOVERY_INITIAL_WAIT="${OPENAI_RECOVERY_INITIAL_WAIT:-30}"
export OPENAI_RECOVERY_MAX_WAIT="${OPENAI_RECOVERY_MAX_WAIT:-600}"
export OPENAI_RECOVERY_BACKOFF="${OPENAI_RECOVERY_BACKOFF:-2.0}"
export OPENAI_RECOVERY_JITTER="${OPENAI_RECOVERY_JITTER:-0.1}"

export SPAGENT_TOOL_RECOVERY_MAX_ATTEMPTS="${SPAGENT_TOOL_RECOVERY_MAX_ATTEMPTS:-0}"
export SPAGENT_TOOL_RECOVERY_MAX_TOTAL_WAIT="${SPAGENT_TOOL_RECOVERY_MAX_TOTAL_WAIT:-300}"
export SPAGENT_TOOL_RECOVERY_INITIAL_WAIT="${SPAGENT_TOOL_RECOVERY_INITIAL_WAIT:-10}"
export SPAGENT_TOOL_RECOVERY_MAX_WAIT="${SPAGENT_TOOL_RECOVERY_MAX_WAIT:-300}"
export SPAGENT_TOOL_RECOVERY_BACKOFF="${SPAGENT_TOOL_RECOVERY_BACKOFF:-2.0}"
export SPAGENT_TOOL_RECOVERY_JITTER="${SPAGENT_TOOL_RECOVERY_JITTER:-0.1}"

export DEPTH_SERVER_URL="${DEPTH_SERVER_URL:-http://127.0.0.1:20019}"
export SEGMENTATION_SERVER_URL="${SEGMENTATION_SERVER_URL:-http://127.0.0.1:20020}"
export DETECTION_SERVER_URL="${DETECTION_SERVER_URL:-http://127.0.0.1:20022}"
export PI3_SERVER_URL="${PI3_SERVER_URL:-http://127.0.0.1:20030}"
export SWINIR_SERVER_URL="${SWINIR_SERVER_URL:-http://127.0.0.1:20032}"
export ORIENT_ANYTHING_SERVER_URL="${ORIENT_ANYTHING_SERVER_URL:-http://127.0.0.1:20034}"

export SPAGENT_USE_REAL_DEPTH="${SPAGENT_USE_REAL_DEPTH:-1}"
export SPAGENT_USE_REAL_SEGMENTATION="${SPAGENT_USE_REAL_SEGMENTATION:-1}"
export SPAGENT_USE_REAL_DETECTION="${SPAGENT_USE_REAL_DETECTION:-1}"
export SPAGENT_USE_REAL_SWINIR="${SPAGENT_USE_REAL_SWINIR:-1}"
export SPAGENT_USE_REAL_ORIENT="${SPAGENT_USE_REAL_ORIENT:-1}"
export SPAGENT_USE_REAL_MOONDREAM="${SPAGENT_USE_REAL_MOONDREAM:-0}"

mkdir -p "${XDG_CACHE_HOME}" "${HF_HOME}" "${TRITON_CACHE_DIR}"
